export default function Terms() {
  return (
    <div
      className="min-h-screen bg-[#08080d] text-white"
      style={{ fontFamily: "'DM Sans', sans-serif" }}
    >
      <nav className="flex items-center justify-between px-6 md:px-12 py-5 border-b border-white/5">
        <a href="/" className="flex items-center gap-2.5">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center text-sm font-bold">
            D
          </div>
          <span className="text-lg font-semibold tracking-tight">DetectAI</span>
        </a>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-zinc-500 text-sm mb-10">Last updated: March 31, 2026</p>

        <div className="space-y-8 text-zinc-400 text-[15px] leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using DetectAI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service. We reserve the right to modify these terms at any time, and your continued use of the Service constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-3">2. Description of Service</h2>
            <p>
              DetectAI is an AI content detection tool that analyzes text to determine the likelihood that it was generated by artificial intelligence. The Service uses multiple detection engines and provides a consensus score. DetectAI is intended as an informational tool and should not be used as the sole basis for academic, legal, or employment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-3">3. Accuracy Disclaimer</h2>
            <p>
              AI detection technology is inherently probabilistic and not 100% accurate. DetectAI provides probability scores and assessments, not definitive conclusions. False positives (human text flagged as AI) and false negatives (AI text not detected) can and do occur. Users should treat detection results as one signal among many and not as conclusive proof of AI authorship. DetectAI is not liable for any decisions made based on its detection results.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-3">4. Free and Premium Plans</h2>
            <p>
              DetectAI offers a free tier with a limited number of daily scans and a premium subscription plan with unlimited scans and additional features. Free usage limits reset daily. Premium subscriptions are billed monthly and can be cancelled at any time. Features and pricing are subject to change with reasonable notice to subscribers.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-3">5. Acceptable Use</h2>
            <p>
              You agree not to use DetectAI for any unlawful purpose, to harass or harm others, to submit malicious content or code, to attempt to reverse-engineer or exploit the Service, to resell or redistribute detection results commercially without permission, or to exceed reasonable usage limits or abuse the free tier through automated means.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-3">6. Intellectual Property</h2>
            <p>
              The DetectAI service, including its design, algorithms, branding, and code, is the intellectual property of DetectAI. You retain full ownership of any text you submit for analysis. We do not claim any rights over your content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-3">7. Limitation of Liability</h2>
            <p>
              DetectAI is provided "as is" without warranties of any kind, whether express or implied. We do not guarantee uninterrupted or error-free operation of the Service. In no event shall DetectAI be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the Service, including but not limited to academic penalties, employment decisions, or reputational harm based on detection results.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-3">8. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time, with or without cause, and with or without notice. Upon termination, your right to use the Service will immediately cease. If you have an active premium subscription, you may be entitled to a prorated refund as described in our Refund Policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-3">9. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of Wyoming, United States, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-zinc-200 mb-3">10. Contact Us</h2>
            <p>
              If you have questions about these Terms of Service, please contact us at support@detectai.com.
            </p>
          </section>
        </div>
      </div>

      <footer className="border-t border-white/5 py-8 px-6">
        <div className="max-w-3xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <span className="text-sm text-zinc-600">&copy; 2026 DetectAI. All rights reserved.</span>
          <div className="flex items-center gap-6">
            <a href="/privacy" className="text-xs text-zinc-500 hover:text-cyan-400 transition-colors">Privacy</a>
            <a href="/terms" className="text-xs text-cyan-400">Terms</a>
            <a href="/refund" className="text-xs text-zinc-500 hover:text-cyan-400 transition-colors">Refund</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
